33 files in Category:Media from Delpher have some sort of source statement in the structured data

https://w.wiki/FMar

------------
file	url	source	kbsourceurl
https://commons.wikimedia.org/entity/M147663108	http://commons.wikimedia.org/wiki/Special:FilePath/1928%20Rotterdams%20Nieuwsblad%20-%20Bewaarschool%20Jan%20Kobellstraat.jpg	http://www.wikidata.org/entity/Q74228490	https://www.flickr.com/photos/marceldouwedekker/49714914502
https://commons.wikimedia.org/entity/M156017813	http://commons.wikimedia.org/wiki/Special:FilePath/ANETA%20photo%20of%20Sarwono%20being%20arrested%20in%20Indonesian%20parliament%20August%201951.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010864068:mpeg21:p002
https://commons.wikimedia.org/entity/M155433444	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201675%20no%20037%20p%202a.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758978
https://commons.wikimedia.org/entity/M155433442	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201675%20no%20037%20p%201%20coat%20of%20arms.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758978
https://commons.wikimedia.org/entity/M155433443	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201675%20no%20037%20p%201a.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758978
https://commons.wikimedia.org/entity/M155433449	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201675%20no%20037.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758978
https://commons.wikimedia.org/entity/M155265026	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201670%20no%20005.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758960
https://commons.wikimedia.org/entity/M157405584	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201670%20no%20005%20p%201.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758960
https://commons.wikimedia.org/entity/M157405586	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201670%20no%20005%20p%202.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010758960
https://commons.wikimedia.org/entity/M156947558	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201758%20no%20053%20p%201%20coat%20of%20arms.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010715581
https://commons.wikimedia.org/entity/M156947559	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201758%20no%20053%20p%202.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010715581
https://commons.wikimedia.org/entity/M156947560	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201758%20no%20053%20p%201.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010715581
https://commons.wikimedia.org/entity/M156947561	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201758%20no%20053.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010715581
https://commons.wikimedia.org/entity/M156316332	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201775%20no%20044.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010711702
https://commons.wikimedia.org/entity/M156316333	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201775%20no%20044%20p%202.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010711702
https://commons.wikimedia.org/entity/M156316331	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201775%20no%20044%20p%201.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010711702
https://commons.wikimedia.org/entity/M147663108	http://commons.wikimedia.org/wiki/Special:FilePath/1928%20Rotterdams%20Nieuwsblad%20-%20Bewaarschool%20Jan%20Kobellstraat.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=ddd:010514210:mpeg21:p021
https://commons.wikimedia.org/entity/M170640196	http://commons.wikimedia.org/wiki/Special:FilePath/1909%20Atlas%20sekolah%20Hindia-Nederland%20map%20of%20Padang%20Highlands%20%28Padangsche%20Bovenlanden%29%20and%20Padang%20Lowlands%20%28Padangsche%20Benedenlanden%29.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMUBL07:000002199:00024
https://commons.wikimedia.org/entity/M155567465	http://commons.wikimedia.org/wiki/Special:FilePath/%27t%20Nieuws%20voor%20Kampen%20vol%20003%20no%20184%20Televisie%20onding%20of%20zegen.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMSAK01:164709033:mpeg21:p00005
https://commons.wikimedia.org/entity/M155567466	http://commons.wikimedia.org/wiki/Special:FilePath/%27t%20Nieuws%20voor%20Kampen%20vol%20003%20no%20184%20De%20%28gelukkige%29%20eenzame.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMSAK01:164709033:mpeg21:p00005
https://commons.wikimedia.org/entity/M155492207	http://commons.wikimedia.org/wiki/Special:FilePath/%27t%20Nieuws%20voor%20Kampen%20vol%20003%20no%20177%20Televisie%20onding%20of%20zegen.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMSAK01:164709026:mpeg21:p00004
https://commons.wikimedia.org/entity/M161129069	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201690-09-23.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMSAA06:165522108
https://commons.wikimedia.org/entity/M161129070	http://commons.wikimedia.org/wiki/Special:FilePath/Amsterdamsche%20Courant%201690-09-23%20p%201%20coat%20of%20arms.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMSAA06:165522108
https://commons.wikimedia.org/entity/M99356924	http://commons.wikimedia.org/wiki/Special:FilePath/Baard%20cornelis.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMKB24:076896000:00004
https://commons.wikimedia.org/entity/M155194181	http://commons.wikimedia.org/wiki/Special:FilePath/Becking%20portrait%20from%20Schoonheyt%20book.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMKB24:071325000:00008
https://commons.wikimedia.org/entity/M171658715	http://commons.wikimedia.org/wiki/Special:FilePath/Antoni%20Brants.png	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMKB24:062646000:00252
https://commons.wikimedia.org/entity/M157553123	http://commons.wikimedia.org/wiki/Special:FilePath/Auteurswet%20%281912%29.pdf	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMKB10:001144002:pdf
https://commons.wikimedia.org/entity/M149876626	http://commons.wikimedia.org/wiki/Special:FilePath/1926%20M.F.L.H.%20Welters%2C%20directeur%20Tiglia%2C%20Tegelen.jpg	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMHNI01:000373022:00005
https://commons.wikimedia.org/entity/M167649975	http://commons.wikimedia.org/wiki/Special:FilePath/B.H.%20Gronewold.png	http://www.wikidata.org/entity/Q74228490	https://resolver.kb.nl/resolve?urn=MMBRON01:267233009:00016
https://commons.wikimedia.org/entity/M18401404	http://commons.wikimedia.org/wiki/Special:FilePath/Advertentie%20Hemsing.jpg	http://www.wikidata.org/entity/Q74228490	http://resolver.kb.nl/resolve?urn=ddd:010656475:mpeg21:p007
https://commons.wikimedia.org/entity/M155129176	http://commons.wikimedia.org/wiki/Special:FilePath/%27t%20Nieuws%20voor%20Kampen%20vol%20003%20no%20169%20Televisie%20onding%20of%20zegen%20illustration.jpg	http://www.wikidata.org/entity/Q74228490	http://resolver.kb.nl/resolve?urn=MMSAK01:164709018:mpeg21:a00077
https://commons.wikimedia.org/entity/M155129177	http://commons.wikimedia.org/wiki/Special:FilePath/%27t%20Nieuws%20voor%20Kampen%20vol%20003%20no%20169%20Televisie%20onding%20of%20zegen.pdf	http://www.wikidata.org/entity/Q74228490	http://resolver.kb.nl/resolve?urn=MMSAK01:164709018:mpeg21:a00077
https://commons.wikimedia.org/entity/M155129333	http://commons.wikimedia.org/wiki/Special:FilePath/%27t%20Nieuws%20voor%20Kampen%20vol%20003%20no%20169%20text%20divider.jpg	http://www.wikidata.org/entity/Q74228490	http://resolver.kb.nl/resolve?urn=MMSAK01:164709018:mpeg21:a00077

-------------

https://commons-query.wikimedia.org/#

SELECT DISTINCT ?file ?url
?source ?kbsourceurl
WITH
{
  SELECT ?file ?title
  WHERE
  {
   SERVICE wikibase:mwapi
    {
    bd:serviceParam wikibase:api "Generator" .
    bd:serviceParam wikibase:endpoint "commons.wikimedia.org" .
    bd:serviceParam mwapi:gcmtitle "Category:Media_from_Delpher" .
    bd:serviceParam mwapi:generator "categorymembers" .
    bd:serviceParam mwapi:gcmtype "file" .
    bd:serviceParam mwapi:gcmlimit "max" .
    ?title wikibase:apiOutput mwapi:title .
    ?pageid wikibase:apiOutput "@pageid" .
    }
    BIND (URI(CONCAT('https://commons.wikimedia.org/entity/M', ?pageid)) AS ?file)
  }
} AS %get_files
WHERE
{
  INCLUDE %get_files
  ?file schema:url ?url.
  #?file p:P7482 ?kbsourceurl
  OPTIONAL {?file p:P7482 [ps:P7482 ?source; pq:P973 ?kbsourceurl].}
}
ORDER BY DESC (?kbsourceurl)


==================
Here’s a clean Commons SPARQL that returns the count of files in Category:Media from Delpher whose SDC has P7482 = Q74228490 (“file available on the internet”):

PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX mwapi:    <https://www.mediawiki.org/ontology#API/>
PREFIX bd:       <http://www.bigdata.com/rdf#>
PREFIX p:        <http://www.wikidata.org/prop/>
PREFIX ps:       <http://www.wikidata.org/prop/statement/>
PREFIX wd:       <http://www.wikidata.org/entity/>

SELECT (COUNT(DISTINCT ?file) AS ?count)
WHERE {
  SERVICE wikibase:mwapi {
    bd:serviceParam wikibase:api "Generator" ;
                    wikibase:endpoint "commons.wikimedia.org" ;
                    mwapi:generator "categorymembers" ;
                    mwapi:gcmtitle "Category:Media from Delpher" ;
                    mwapi:gcmtype "file" ;
                    mwapi:gcmlimit "max" .
    ?pageid wikibase:apiOutput "@pageid" .
  }
  BIND( IRI(CONCAT("https://commons.wikimedia.org/entity/M", ?pageid)) AS ?file )
  ?file p:P7482 ?st .
  ?st ps:P7482 wd:Q74228490 .
}